'on':
  pull_request: {}
  workflow_dispatch: {}
concurrency: '1'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        id: Checkout
      - name: Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-yarn
          path: .yarn/cache
        id: Cache
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
          cache: yarn
        id: SetupNode
      - run: yarn config set --home npmAuthToken ${{ secrets.NPM_TOKEN }}
        id: YarnAuth
      - name: Install Dependencies
        run: yarn install --immutable
        id: Install
      - name: Build
        run: yarn build
        id: Build
      - name: Find mutations
        run: |-
          git add .
          git diff --staged --patch --exit-code > .repo.patch || echo "::set-output name=self_mutation_happened::true"
        id: FindSelfMutationStep
      - name: Upload Patch
        uses: actions/upload-artifact@v2
        if: steps.self_mutation.outputs.self_mutation_happened
        with:
          name: ${{ .repo.patch }}
          path: ${{ runner.temp }}
        id: UploadMutations
      - name: Fail build on mutation
        if: steps.self_mutation.outputs.self_mutation_happened
        run: >-
          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will
          need to update your branch."

          cat .repo.patch

          exit 1
        id: FailOnSelfMutationStep
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        id: Checkout
      - name: Report
        uses: ArtiomTr/jest-coverage-report-action@v2
        id: Download
